name: Build and Push React PerfAnalytics Frontend Docker

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ secrets.GHCR_USERNAME }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/arm64
        push: true
<<<<<<< HEAD
        tags: ghcr.io/${{ secrets.GHCR_USERNAME }}/react-perfanalytics:latest
=======
        tags: ghcr.io/${{ secrets.GHCR_USERNAME }}/react-perfanalytics:latest
>>>>>>> 6332a6c03d8426d7773c76918ed56def37fc62fe
